server:
  port: 8080

spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3307/pium

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR