server:
  port: 8080

spring:
  profiles:
    active: local

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: true

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR

# backend_spring/src/main/resources/application.yml
jwt:
  secret: ${JWT_SECRET}
#jwt:
#  secret: "thisIsMySuperLongSecretKeyForJWTToken987654321!"

cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    s3:
      bucket-name: ${BUCKET_NAME}
    region:
      static: ap-northeast-2
    stack:
      auto: false

# 강제로 UTF-8 인코딩
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true
