server:
  port: 8080

spring:
  profiles:
    active: local
# 강제로 UTF-8 인코딩
http:
  encoding:
    charset: UTF-8
    enabled: true
    force: true

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR

# backend_spring/src/main/resources/application.yml
jwt:
  secret: ${JWT_SECRET}

