server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pium
    username : root
    password: hsgty588123s

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.web.multipart: DEBUG
    org.springframework.web.servlet.DispatcherServlet: DEBUG
    org.hibernate: ERROR